modified:   makesrc

diff --git a/makesrc b/makesrc
--- a/makesrc
+++ b/makesrc
@@ -1,17 +1,19 @@
 #!/usr/bin/env bash
 
-TGTBUILD_DEV=$build_dev
-TGTBUILD_DIR=$build_dir
-TGTBUILD_TGT=$build_tgt
-CCTC_USR=$toolbox_user
-CCTC_DIR=$toolbox_dir
-SOURCEMAN_GET=$source_get
-SOURCEMAN_DIR=$source_dir
-SOURCEMAN_KEYRING=/home/$CCTC_USR/.gnupg/sourceman.keys
-CCTC_TBX=''
-#MAKEFLAGS=$makeflags
+:(){ #?
+		TGTBUILD_DEV=$build_dev
+		TGTBUILD_DIR=$build_dir
+		TGTBUILD_TGT=$build_tgt
+		CCTC_USR=$toolbox_user
+		CCTC_DIR=$toolbox_dir
+		SOURCEMAN_GET=$source_get
+		SOURCEMAN_DIR=$source_dir
+		SOURCEMAN_KEYRING=/home/$CCTC_USR/.gnupg/sourceman.keys
+		CCTC_TBX=''
+		#MAKEFLAGS=$makeflags
+}
 
-args=('-h' '--help' '-q' '--query' '-i' '--interactive')
+SRCBUILD_CONFIG=${SRCBUILD_USER_CONF:-$HOME/.config/srcman/makesrc.conf}
 
 # exit codes 
 EX_OK=0				# completed without error
@@ -22,15 +24,51 @@ EX_NOHOST=68		# error - source get failed
 EX_DATAERR=65		# error - source verification failed (.sig, checksums, etc.)
 EX_CANTCREAT=73		# error - makesrc failed - cannot build source
 
+# perm/sec
+readonly _UID="$(id -u "$USER")"
+
+# color values
+readonly green='\e[0;32m'
+readonly yellow='\e[0;33m'
+readonly magenta='\e[0;35m'
+readonly Bold='\e[1m'
+readonly Bred='\e[1;31m'
+readonly Bgreen='\e[1;32m'
+readonly Byellow='\e[1;33m'
+readonly Bblue='\e[1;34m'
+readonly Bmagenta='\e[1;35m'
+readonly reset='\e[0m'
+
+# vebosity/ux
+_message() { [ $QUIET = 0 ] &&:; }
+_warning() { [ $QUIET = 0 ] &&:; }
+_error() { echo -e "$(basename 0): ${Bred}ERROR: ${reset} ${*}" >&2; }
+_die() { _error ${@} && exit $_EX; }
+
+args=('-h' '--help' '-q' '--query' '-i' '--interactive')
+ret=$?
+
+_has_dependencies() {
+	typeset -a deps
+	deps=($@)
+
+	for a in $deps
+	do
+			$deps=${depends[*]}
+			[ -n $deps ] && [ $deps -gt 0 ] && { :; } 
+	done
+}
+
+_tmp_space() {	# provide a random space in shared memory to use/access
+	local tmpf
+	tmpfile
+
+	tmpf=$(mktemp -u "$SECURE_TMPDIR/XXXXXXXXXXXXXXXXXXXX")
+
+}
 usage()
 {
-		largs()
-		{
-				for x in ${args[@]}
-						do
-								echo -n "[$x] "
-						done
-		}
+		largs() { for x in ${args[@]}; do echo -n "[$x] "; done; }
 		usage_long()
 		{
 				echo -e "Usage: $(basename $0) [OPTIONS]... [CCOPTIONS]... [SRCBUILD]"
@@ -45,6 +83,8 @@ usage()
 		{ 
 				echo -e "$(basename $0): invalid command\nUsage: $(largs)... [SRCBUILD]" 
 		}
+
+
 }
 
 srcsrcbuild() # source SRCBUILD
@@ -57,18 +97,19 @@ srcsrcbuild() # source SRCBUILD
 		fi
 }
 
-srcinfo() # parse & echo various different $vars to STDOUT
+srcinfo() # read SRCBUILD "info" ($vars)
 {
 		info_print()
 		{
-				echo -e "\e[0;31mSOURCE\e[0m\n"
+				local _color=$Bred
+				echo -e "${_color}SOURCE${reset}\n"
 				echo -e "\t$srcname - ($srcver)\n"
-				echo -e "\e[0;31mINFO\e[0m\n"
+				echo -e "${_color}INFO${reset}\n"
 				echo -e "  $info\n"
-				echo -e "\e[0;31mPROJECT HOME\e[0m\n"
+				echo -e "${_color}PROJECT HOME${reset}\n"
 				echo -e "  $srcurl\n"	
-				echo -e "\e[0;31mLICENSE\e[0m\n"
-				echo -e "  \e[1;31mThis project is licenced under the following:\e[0m ${srccpy[*]}\n"
+				echo -e "${_color}LICENSE${reset}"
+				echo -e "  ${_color}This project is licenced under the following:${reset} ${srccpy[*]}\n"
 		};srcsrcbuild; info_print;
 }
 
@@ -230,7 +271,7 @@ makesrc() # make a source-build from a SRCBUILD
 
 config_file_options() # TESTING makesrc config file
 {
-	[ -f $HOME/.config/makesrc/config ] || [ -f ./config ]
+	[ -e $SRCBUILD_CONF ] && { source $SRCBUILD_CONF; }
 }
 
 cc_toolbox_optins() # TESTING system cc_toolbox options
