modified:   README 	modified:   _usage_error 	modified:   config 	modified:   get_info 	modified:   makesrc

diff --git a/makesrc b/makesrc
--- a/makesrc
+++ b/makesrc
@@ -3,13 +3,13 @@
 readonly VERSION='2.0'
 
 # exit codes 
-readonly EX_OK='0'				# completed without error
-readonly EX_USAGE='64'			# error - general command line usage error 
-readonly EX_NOPERM='70'			# error - improper permissions - (root permissions needed)
-readonly EX_UNAVAILABLE='69'	# error - improper input - (SRCBUILD not found)
-readonly EX_NOHOST='68'			# error - source get failed
-readonly EX_DATAERR='65'		# error - corrupt data (.sig, checksums, etc.)
-readonly EX_CANTCREATE='73'		# error - makesrc failed - cannot build source
+readonly EXIT_OK='0'				# completed without error
+readonly EXIT_USAGE='64'			# error - general command line usage error 
+readonly EXIT_DATAERR='65'			# error - corrupt data (.sig, checksums, etc.)
+readonly EXIT_NOHOST='68'			# error - source get failed
+readonly EXIT_UNAVAILABLE='69'		# error - improper input - (SRCBUILD not found)
+readonly EXIT_NOPERM='70'			# error - improper permissions - (root permissions needed)
+readonly EXIT_CANTCREATE='73'		# error - makesrc failed - cannot build source
 
 # permissions/security
 readonly _UID="$(id -u "$USER")"
@@ -30,10 +30,10 @@ readonly bold_blue=${bold}${blue}
 readonly bold_magenta=${bold}${magenta}
 
 # ux
-_message() { [ $QUIET = 0 ] && echo -e "${bold_green}*${reset} ${*}" >&2; }
-_warning() { [ $QUIET = 0 ] && echo -e "${bold_yellow}[W]${reset} ${*}" >&2; }
-_error() { [ $QUIET = 0 ] && echo -e "[$(basename $0)]-${bold_red}[X]:${reset} ${*}" >&2; }
-_die() { [ $QUIET = 0 ] && { _error ${@} exit $_EX; } || exit $_EX; }
+_message() { [ $QUIET = 0 ] && echo -e "\t${bold_green}*${reset} ${*}" >&2; }
+_warning() { [ $QUIET = 0 ] && echo -e "\t${bold_yellow}[W]${reset} ${*}" >&2; }
+_error() { [ $QUIET = 0 ] && echo -e "\t${bold_red}[X]${reset} ${*}" >&2; }
+_die() { [ $QUIET = 0 ] && { _error "${@}" && exit $_EX; } || exit $_EX; }
 
 source "_tmp_space"
 source "_version"
@@ -73,8 +73,8 @@ DEBUG=0
 DEFAULT=0
 
 # Options
-small_options="hvsq::c:x:"
-long_options="help,version,silent,query::,config::,cc:"
+small_options="c:si::x:hv"
+long_options="config:,silent,info::,cc:,help,version"
 options="$(getopt -o $small_options -l $long_options -n "$SRCBUILD" -- "$@")"
 
 # No options
@@ -94,12 +94,12 @@ while [ $? -eq 0 ]
 do
 		case "$1" in
 				'-c'|'--config') 
-						if [ ! -z "$2" ];
+						if [ -n $2 ];
 						then
 								MAKESRC_USER_CONFIG="$2"
 								DEFAULT=1
 						else
-								_EX=$EX_USAGE; _die "Fatal error - no valid config file specified"
+								_EX=$EXIT_USAGE; _die "Fatal error - no valid user configuration file specified"
 						fi
 						shift 2
 						continue
@@ -109,9 +109,9 @@ do
 						shift 2
 						continue
 						;;
-				'-q'|'--query')
+				'-i'|'--info')
 						case "$2" in
-								# long option - show more info (TODO)
+								# long option - show more info
 								'-a'|'--all')
 									    :#get_info_long	
 										;;
